baseURL = "https://cv.marcoscarceles.com/"
languageCode = "en-gb"
defaultContentLanguage = "en"
theme = "almeida-cv"
title = "Marcos CÃ¡rceles - Resume"

enableRobotsTXT = true
enableEmoji = true
disableKinds = ["page", "section", "taxonomy", "term", "RSS", "sitemap"]

[params]
enableMetaTags = true

colorLight = "#fff"
colorDark = "#666"

colorPageBackground = "#ddd"

colorPrimary = "#088"
colorSecondary = "#aaa"

colorIconPrimary = "#fff"
colorIconBackground = "#088"

#colorPrimaryText = "#333"
colorRightColumnBackground = "#f5f5f5"
colorRightColumnHeadingText = "#666"
colorRightColumnBodyText = "#666"
colorRightColumnIconPrimary = "#fff"
colorRightColumnIconBackground = "#088"

pages = 2

swapColumns = true